// ── Redis Singleton + Atomic Publisher ────────────────────────────
// Single connection pool shared across all server-side consumers.
// The Publisher Invariant guarantees that every live event is
// atomically appended to the Stream AND broadcast via Pub/Sub
// in a single Redis round-trip using a Lua script.

import Redis from "ioredis";

// ── Connection ──────────────────────────────────────────────────

const REDIS_URL = process.env.REDIS_URL || "redis://127.0.0.1:6379";

function createRedisClient(): Redis {
  const client = new Redis(REDIS_URL, {
    maxRetriesPerRequest: 3,
    enableReadyCheck: true,
    lazyConnect: false,
    retryStrategy(times) {
      // Exponential backoff capped at 5s
      return Math.min(times * 200, 5000);
    },
  });

  client.on("error", (err) => {
    console.error(
      JSON.stringify({
        severity: "ERROR",
        component: "redis",
        event: "connection_error",
        message: err instanceof Error ? err.message : String(err),
        timestamp: new Date().toISOString(),
      }),
    );
  });

  client.on("connect", () => {
    console.log(
      JSON.stringify({
        severity: "INFO",
        component: "redis",
        event: "connected",
        url: REDIS_URL.replace(/\/\/.*@/, "//***@"), // redact credentials
        timestamp: new Date().toISOString(),
      }),
    );
  });

  return client;
}

// Module-scoped singleton — one gRPC channel pool per process
let _redis: Redis | null = null;

export function getRedis(): Redis {
  if (!_redis) {
    _redis = createRedisClient();
  }
  return _redis;
}

// Separate subscriber client (ioredis requires a dedicated connection for SUBSCRIBE)
let _subscriber: Redis | null = null;

export function getRedisSubscriber(): Redis {
  if (!_subscriber) {
    _subscriber = createRedisClient();
  }
  return _subscriber;
}

// ── Lua Script: Atomic XADD + PUBLISH ───────────────────────────
// Keys: [stream_key, pubsub_channel]
// Args: [max_stream_length, raw_json_payload]
//
// This script executes entirely in the Redis main thread as an
// atomic operation. It:
//   1. Appends the event to the Stream (XADD) with auto-generated ID
//   2. Uses MAXLEN ~ for O(1) bounded growth (no OOM risk)
//   3. Injects the Redis-generated ID into the JSON payload
//   4. Broadcasts the enriched payload via PUBLISH
//
// Total complexity: O(1) — negligible main-thread block (microseconds).

const ATOMIC_BROADCAST_LUA = `
  -- Append to stream with approximate MAXLEN cap
  local id = redis.call('XADD', KEYS[1], 'MAXLEN', '~', ARGV[1], '*', 'data', ARGV[2])

  -- Inject the Redis-generated stream ID into the JSON payload
  -- We slice the trailing '}' and append the id field
  local rawJson = ARGV[2]
  local broadcastPayload = string.sub(rawJson, 1, -2) .. ',"id":"' .. id .. '"}'

  -- Broadcast to all connected Cloud Run containers
  redis.call('PUBLISH', KEYS[2], broadcastPayload)

  return id
`;

// Define the custom command on first access
let _commandDefined = false;

function ensureAtomicBroadcastCommand(client: Redis): void {
  if (_commandDefined) return;
  client.defineCommand("atomicBroadcast", {
    numberOfKeys: 2,
    lua: ATOMIC_BROADCAST_LUA,
  });
  _commandDefined = true;
}

// Extend ioredis types for our custom command
declare module "ioredis" {
  interface Redis {
    atomicBroadcast(
      streamKey: string,
      pubsubChannel: string,
      maxLen: string,
      payload: string,
    ): Promise<string>;
  }
}

// ── Publisher API ────────────────────────────────────────────────

const STREAM_KEY = process.env.LEDGER_STREAM_KEY || "ledger:stream";
const PUBSUB_CHANNEL = process.env.LEDGER_PUBSUB_CHANNEL || "ledger:pubsub";
const MAX_STREAM_LENGTH = Number(process.env.LEDGER_MAX_STREAM_LENGTH || 5000);

/**
 * Publisher Invariant:
 * Every live event MUST be routed through this function.
 * It enforces Snapshot-Convergent semantics with Gap-Free bounded replay.
 *
 * Guarantees:
 *   - XADD and PUBLISH execute atomically (single Lua eval)
 *   - The stream ID generated by Redis is exactly what clients receive
 *   - Stream is bounded to MAX_STREAM_LENGTH entries (MAXLEN ~)
 *   - No "ghost event" race: crash after XADD but before PUBLISH is impossible
 *
 * @returns The exact Redis stream ID (e.g. "1713557193000-0")
 */
export async function publishLedgerEvent(
  eventData: Record<string, unknown>,
): Promise<string> {
  const redis = getRedis();
  ensureAtomicBroadcastCommand(redis);

  const id = await redis.atomicBroadcast(
    STREAM_KEY,
    PUBSUB_CHANNEL,
    String(MAX_STREAM_LENGTH),
    JSON.stringify(eventData),
  );

  return id;
}

// ── Stream Replay ───────────────────────────────────────────────

/**
 * Fetch missed events from the stream starting after `lastEventId`.
 * Used by SSE reconnection to fill the gap between disconnect and reconnect.
 *
 * @param lastEventId - The last Redis stream ID the client acknowledged
 * @param count - Maximum number of entries to return (bounded replay)
 * @returns Array of [streamId, eventData] tuples
 */
export async function replayLedgerEvents(
  lastEventId: string,
  count = 200,
): Promise<Array<{ id: string; data: string }>> {
  const redis = getRedis();
  const results = await redis.xrange(
    STREAM_KEY,
    `(${lastEventId}`, // exclusive start
    "+",
    "COUNT",
    count,
  );

  return results.map(([id, fields]) => {
    // fields is [key, value, key, value, ...]
    const dataIndex = fields.indexOf("data");
    const data = dataIndex >= 0 && dataIndex + 1 < fields.length
      ? fields[dataIndex + 1]
      : "{}";
    return { id, data };
  });
}

// ── Constants Export ─────────────────────────────────────────────

export { STREAM_KEY, PUBSUB_CHANNEL, MAX_STREAM_LENGTH };
