const fs = require("fs");
const payload = {
  "candidates": [
    // BATCH 2
    { "Candidate ID": "1374541", "Name": "Bianca Hicks", "Email": "dg83773@gmail.com", "Profession": "CNA", "Specialty": "MS(7)" },
    { "Candidate ID": "1430669", "Name": "Medina Muhammad", "Email": "Medina.muhammad@yahoo.com", "Profession": "MA", "Specialty": "MED-ASST(24)" },
    { "Candidate ID": "1462476", "Name": "Molly Weishahn", "Email": "mkmweishahn247@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(11)" },
    { "Candidate ID": "1645063", "Name": "Kimberly Williams", "Email": "kimberlywil1979@gmail.com", "Profession": "MA", "Specialty": "MED-ASST(24)" },
    { "Candidate ID": "1725501", "Name": "Maame Tiwaah Ahenkora", "Email": "maameasare4@gmail.com", "Profession": "PHM", "Specialty": "PhrmTech-Inp(4) Pharm Tech(4)" },
    { "Candidate ID": "2461331", "Name": "Christopher Julin", "Email": "cjjtaytay@yahoo.com", "Profession": "LAB", "Specialty": "PHLEB(3)" },
    { "Candidate ID": "2666714", "Name": "Fontaine Joseph", "Email": "josephfontaine800@gmail.com", "Profession": "RN", "Specialty": "MS(4)" },
    { "Candidate ID": "2816911", "Name": "Nathan Welch", "Email": "nathanwelch20@gmail.com", "Profession": "LAB", "Specialty": "MLT(2)" },
    { "Candidate ID": "3015525", "Name": "Rachel M Henderson", "Email": "rmpurnell2018@gmail.com", "Profession": "RN", "Specialty": "ER(3)" },
    { "Candidate ID": "3196969", "Name": "Anna Alfred", "Email": "anna.chakkalackal@yahoo.com", "Profession": "RN", "Specialty": "CASEMGR(17) ONC(2) UTIL(1)" },
    { "Candidate ID": "3200921", "Name": "Savannah Woodward", "Email": "savdwood22@aol.com", "Profession": "LVN", "Specialty": "CORR(4) AMB(4) URGNT(4) LVNLTAC(4) COVIDTest(4) LTC(1)" },
    { "Candidate ID": "3340538", "Name": "Kalaya Cane", "Email": "layak05146@gmail.com", "Profession": "RAD-CARD", "Specialty": "CTTECH(2) XRY-TECH(2)" },
    { "Candidate ID": "3355024", "Name": "Mya Marshall", "Email": "myamardhal72@gmail.com", "Profession": "MA", "Specialty": "MED-ASST(24)" },
    { "Candidate ID": "3710777", "Name": "Emily Torres", "Email": "emily.torres.x5@gmail.com", "Profession": "RN", "Specialty": "STEP(1) PRE/POST(2)" },
    { "Candidate ID": "4010599", "Name": "Jerry Moran", "Email": "jermorans@yahoo.com", "Profession": "RESP", "Specialty": "RRT(15)" },
    { "Candidate ID": "4020942", "Name": "Anthony Iyile", "Email": "tonyiyile@yahoo.com", "Profession": "RN", "Specialty": "ER(4) STEP(2) MICU(11) CVICU(1) SICU(2)" },
    { "Candidate ID": "4064516", "Name": "Azjah Brown", "Email": "azjahbrown50@gmail.com", "Profession": "SURG", "Specialty": "STERILE-TECH(3)" },
    { "Candidate ID": "4071378", "Name": "Kimberly Shante Brown", "Email": "shantemcdonald35@yahoo.com", "Profession": "LAB", "Specialty": "PHLEB(3)" },
    { "Candidate ID": "4119492", "Name": "Dallas Mechelle Bower-Franklin", "Email": "dallas_mechelle_14@yahoo.com", "Profession": "RN", "Specialty": "TELE(5) IMC(5) MS/TELE(5) MS-NEUR(5)" },
    { "Candidate ID": "4125740", "Name": "Keante Dixon", "Email": "dkeante@yahoo.com", "Profession": "PHM", "Specialty": "PHRMTECH(11)" },
    { "Candidate ID": "4197940", "Name": "Jahanna Perry-McElroy", "Email": "jada212000@gmail.com", "Profession": "RAD-CARD", "Specialty": "CTTECH(9)" },
    { "Candidate ID": "4261730", "Name": "Smith Vazquez", "Email": "swas7980@gmail.com", "Profession": "RESP", "Specialty": "RRT(14)" },
    { "Candidate ID": "4392476", "Name": "Morgan King", "Email": "monk8687@gmail.com", "Profession": "LVN", "Specialty": "LTC(4) CLINIC(4) AMB(4) OUTP-CLNC(4)" },
    { "Candidate ID": "4430485", "Name": "Trina Anne Wong", "Email": "wongtrinaanne@gmail.com", "Profession": "RN", "Specialty": "TELE(6)" },
    { "Candidate ID": "4690382", "Name": "Esmeralda Lagunes Cedillo", "Email": "esmielagun1999@yahoo.com", "Profession": "MA", "Specialty": "MED-ASST(24)" },

    // BATCH 3
    { "Candidate ID": "4997287", "Name": "Arfang Fatty", "Email": "fattyarfang@gmail.com", "Profession": "PCT", "Specialty": "PCTECH(3)" },
    { "Candidate ID": "5000000", "Name": "Serin Gbaba", "Email": "niresjt@hotmail.com", "Profession": "PHM", "Specialty": "PhrmTech-Inp(2) Pharm Tech(1)" },
    { "Candidate ID": "5037755", "Name": "Aemberly Montilla", "Email": "aemee128@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(7)" },
    { "Candidate ID": "380299", "Name": "Gerald Newman", "Email": "geraldnewman@live.com", "Profession": "RAD-CARD", "Specialty": "CTTECH(25) XRY-TECH(25)" },
    { "Candidate ID": "431182", "Name": "Christine Celella", "Email": "ccelella@gmail.com", "Profession": "RN", "Specialty": "MS(12)" },
    { "Candidate ID": "512694", "Name": "Tonia Teasley", "Email": "Tonia00@live.com", "Profession": "LVN", "Specialty": "LTC(8)" },
    { "Candidate ID": "540406", "Name": "Karon Hightower-McFarlin", "Email": "karonmcfarlin@rocketmail.com", "Profession": "RN", "Specialty": "MB/PP(12) VACC(1)" },
    { "Candidate ID": "553672", "Name": "Lakiesha Williams", "Email": "wlakiesha25@yahoo.com", "Profession": "LVN", "Specialty": "LTC(11) MS(11)" },
    { "Candidate ID": "684652", "Name": "Kathy Waldron", "Email": "ornurse9094@hotmail.com", "Profession": "RN", "Specialty": "OR(18) OUTPSURG(18)" },
    { "Candidate ID": "684735", "Name": "Chiara Dugas", "Email": "chiara_mone@yahoo.com", "Profession": "RN", "Specialty": "LTC(5) PEDS(5) CORR(5)" },
    { "Candidate ID": "760544", "Name": "Suzanne Dixon", "Email": "Smdd80@gmail.com", "Profession": "RN", "Specialty": "MS(15) TELE(9)" },
    { "Candidate ID": "790534", "Name": "Alecia Steptoe", "Email": "aleciasteptoe@gmail.com", "Profession": "RN", "Specialty": "HH(3) MS(6) STEP(3)" },
    { "Candidate ID": "796846", "Name": "Lauren Gulbrandsen", "Email": "laurengulbrandsenrn@gmail.com", "Profession": "RN", "Specialty": "ER(4)" },
    { "Candidate ID": "798323", "Name": "Bobbie Eubanks", "Email": "Stormey20@gmail.com", "Profession": "RESP", "Specialty": "RRT(23) RRTPICU(4)" },
    { "Candidate ID": "800035", "Name": "Elexis Waugh", "Email": "waughelexis90@gmail.com", "Profession": "SoclSrvcs", "Specialty": "LCSW(1) LMSW(7) MSW(7)" },
    { "Candidate ID": "806576", "Name": "Sarah Hughes", "Email": "sehugh26@gmail.com", "Profession": "RN", "Specialty": "ER(2) PACU(4) ONC(5)" },
    { "Candidate ID": "857592", "Name": "Justin Lonergan", "Email": "Lonerganj@gmail.com", "Profession": "SURG", "Specialty": "OR-TECH(22)" },
    { "Candidate ID": "861032", "Name": "David Fallmaier", "Email": "Emt420@sbcglobal.net", "Profession": "RESP", "Specialty": "RRT(21)" },
    { "Candidate ID": "871309", "Name": "Adrienne Bristow", "Email": "Slanteyebristow@yahoo.com", "Profession": "SURG", "Specialty": "OR-TECH(14)" },
    { "Candidate ID": "892058", "Name": "Heidi Nitz", "Email": "heidinitz@gmail.com", "Profession": "RN", "Specialty": "ORTHO(4) MS/Tele Float(4) AcuCareFloat(3)" },
    { "Candidate ID": "950461", "Name": "Josil Tayson", "Email": "josiltayson@yahoo.com", "Profession": "RESP", "Specialty": "RRT(9)" },
    { "Candidate ID": "951135", "Name": "Macmillan Dalla", "Email": "macdalla79@gmail.com", "Profession": "PCT", "Specialty": "PCTECH(20)" },
    { "Candidate ID": "951985", "Name": "Kim Hoang", "Email": "khoang113@gmail.com", "Profession": "RN", "Specialty": "ICU(1) ER(2) PEDS-ER(1)" },
    { "Candidate ID": "970123", "Name": "LISSA Hatley", "Email": "lissachristen@gmail.com", "Profession": "RN", "Specialty": "" },
    { "Candidate ID": "991913", "Name": "Jade Byrd", "Email": "jnbyrd29@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(9) RRT(9) RRTPICU(9) RRTPEDS(9)" },

    // BATCH 4
    { "Candidate ID": "1023902", "Name": "Gary Deshong", "Email": "gdeshng@verizon.net", "Profession": "RESP", "Specialty": "RRT-NICU(25) RRT(25)" },
    { "Candidate ID": "1114673", "Name": "Malik Logan", "Email": "maliklogan52@yahoo.com", "Profession": "RN", "Specialty": "TRAUMAICU(2)" },
    { "Candidate ID": "1193043", "Name": "ANTOINETTE ROY", "Email": "antoinettelatisha@yahoo.com", "Profession": "RN", "Specialty": "" },
    { "Candidate ID": "1260268", "Name": "Tiffany Howard", "Email": "thoward0603@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(10) RRT(10)" },
    { "Candidate ID": "1264637", "Name": "Linda Wesaw", "Email": "lwesaw@gmail.com", "Profession": "RESP", "Specialty": "CRT(14)" },
    { "Candidate ID": "1304656", "Name": "Rocio Ramirez", "Email": "rocioramirez0012@gmail.com", "Profession": "RN", "Specialty": "ER(4)" },
    { "Candidate ID": "1322428", "Name": "Emily Welch", "Email": "ewelch977@gmail.com", "Profession": "RN", "Specialty": "ER(12)" },
    { "Candidate ID": "1328313", "Name": "Shauntaya Myers", "Email": "shauntaya18@gmail.com", "Profession": "LVN", "Specialty": "ADMIN(1) HH(7)" },
    { "Candidate ID": "1342643", "Name": "Esai Sida", "Email": "esai_sida@yahoo.com", "Profession": "RN", "Specialty": "IV-RAD(4) NEURO-ICU(5)" },
    { "Candidate ID": "1400381", "Name": "Pamela Moyer", "Email": "pmoyer01@comcast.net", "Profession": "RESP", "Specialty": "RRT-NICU(25) RRT(25)" },
    { "Candidate ID": "1402252", "Name": "Perlita Fajardo", "Email": "pearl193620@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(16) RRT(16) RRTPICU(16)" },
    { "Candidate ID": "1403641", "Name": "Kenneth Squazzo", "Email": "kfsquazzo1@gmail.com", "Profession": "SURG", "Specialty": "GIENDOTCH(9)" },
    { "Candidate ID": "1403674", "Name": "Stephanie Wesolek", "Email": "stephaniewesolek5@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(4)" },
    { "Candidate ID": "1411942", "Name": "Jocelyn Bular", "Email": "jocelyn.bular@yahoo.com", "Profession": "RN", "Specialty": "ER(4)" },
    { "Candidate ID": "1413071", "Name": "Amy Kammerdiener", "Email": "kammerdiener.amy@gmail.com", "Profession": "RAD-CARD", "Specialty": "XRY-TECH(25)" },
    { "Candidate ID": "1442139", "Name": "Cynthia Ononobi", "Email": "kesserezih2004@yahoo.com", "Profession": "RN", "Specialty": "MS(6) IMC(6)" },
    { "Candidate ID": "1442469", "Name": "Ifeoma Ofili", "Email": "ifeoma_ofili@yahoo.com", "Profession": "RESP", "Specialty": "RRT(7)" },
    { "Candidate ID": "1460224", "Name": "Biruktawit Bati", "Email": "biruktawit23@yahoo.com", "Profession": "RESP", "Specialty": "RRT(4)" },
    { "Candidate ID": "1461442", "Name": "Kinetra Peters", "Email": "kinetra.peters@gmail.com", "Profession": "PHM", "Specialty": "PhrmTech-Inp(14) Pharm Tech(6)" },
    { "Candidate ID": "1468710", "Name": "Cindy Ayala", "Email": "cindyayala.yta@gmail.com", "Profession": "RN", "Specialty": "OR(5)" },
    { "Candidate ID": "1472106", "Name": "Antwonette Johnson", "Email": "antwonettej@yahoo.com", "Profession": "LVN", "Specialty": "HH(4)" },
    { "Candidate ID": "1478260", "Name": "Teima Gayflor", "Email": "gayflorsmile@yahoo.com", "Profession": "SURG", "Specialty": "STERILE-TECH(5)" },
    { "Candidate ID": "1500533", "Name": "Ayanna Washington", "Email": "washingtonayanna91@yahoo.com", "Profession": "LVN", "Specialty": "HH(1) LTC(2) BH(6)" },
    { "Candidate ID": "1503947", "Name": "Chequita McClain", "Email": "KITAT80@YAHOO.COM", "Profession": "RESP", "Specialty": "RRT(20) RRTPICU(5)" },
    { "Candidate ID": "1525451", "Name": "Giordani Belizaire", "Email": "belizaireg@yahoo.com", "Profession": "RESP", "Specialty": "RRT-NICU(10) RRT(10) RRTPICU(10)" },
    { "Candidate ID": "1527267", "Name": "Shanonn Barr", "Email": "twobirdshow@gmail.com", "Profession": "LAB", "Specialty": "PHLEB(12) Lab Asst(7)" },
    { "Candidate ID": "1534729", "Name": "Shamaya Lyles", "Email": "shamayalyles@icloud.com", "Profession": "RN", "Specialty": "MS(3) MS/TELE(3)" },
    { "Candidate ID": "1551687", "Name": "Julia Goelz", "Email": "goelzj93@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(9) RRT(9)" },
    { "Candidate ID": "1562877", "Name": "Mamanagbe Keita", "Email": "brownkeita@aol.com", "Profession": "CNA", "Specialty": "ER(2) MS(3) BH(2)" },
    { "Candidate ID": "1566408", "Name": "Shawntina Nixon", "Email": "Shawntinanixon@gmail.com", "Profession": "LAB", "Specialty": "PHLEB(25) Lab Asst(20)" },
    { "Candidate ID": "1570787", "Name": "Bradley Orengo", "Email": "bradley.orengo@gmail.com", "Profession": "RESP", "Specialty": "RRT(8)" },
    { "Candidate ID": "1571230", "Name": "Lourdes Shinn", "Email": "lour_car@yahoo.com", "Profession": "LVN", "Specialty": "MS(11) CORR(1)" },
    { "Candidate ID": "1574434", "Name": "Priscilla Nguyen", "Email": "priscillanguyen12@gmail.com", "Profession": "RN", "Specialty": "BH(1) AMB(1)" },
    { "Candidate ID": "1577664", "Name": "Eyerusalem Ashenafi", "Email": "eyerusalem1275@gmail.com", "Profession": "RESP", "Specialty": "RRT(4)" },
    { "Candidate ID": "1584801", "Name": "Annette Bookman", "Email": "bookmanannette@ymail.com", "Profession": "LVN", "Specialty": "LTC(25)" },

    // BATCH 5
    { "Candidate ID": "1585155", "Name": "Brittany Dunn", "Email": "Britt1043@gmail.com", "Profession": "RN", "Specialty": "ADMIN(2) MS(3) NICU(1)" },
    { "Candidate ID": "1606355", "Name": "Lisa Sprague", "Email": "shortstuff2549@gmail.com", "Profession": "RN", "Specialty": "L& D(11) MB/PP(2) ANTEP(9)" },
    { "Candidate ID": "1615169", "Name": "Keith Combs", "Email": "keithpcombs@gmail.com", "Profession": "RAD-CARD", "Specialty": "XRY-TECH(4)" },
    { "Candidate ID": "1624566", "Name": "Sabrina Allahrakha", "Email": "sabsab01@me.com", "Profession": "RN", "Specialty": "MS/TELE(14)" },
    { "Candidate ID": "1625033", "Name": "Olakunle Oladipupo", "Email": "taye.olad@yahoo.com", "Profession": "RESP", "Specialty": "RRT-NICU(3)" },
    { "Candidate ID": "1625284", "Name": "Jared DeVico", "Email": "jaredldevico@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(4) RRT(7)" },
    { "Candidate ID": "1654096", "Name": "Gustavo Rosales", "Email": "Rgustavo1r1@gmail.com", "Profession": "RESP", "Specialty": "RRT(4)" },
    { "Candidate ID": "1654283", "Name": "Kaitlyn Neiheisel", "Email": "kaitmnei@gmail.com", "Profession": "RN", "Specialty": "MS(3)" },
    { "Candidate ID": "1655339", "Name": "Alana Carter", "Email": "alanajanece@gmail.com", "Profession": "RN", "Specialty": "TELE(1)" },
    { "Candidate ID": "1660378", "Name": "Debora Smith", "Email": "aldeb345@verizon.net", "Profession": "RN", "Specialty": "MS(4) MS/TELE(4)" },
    { "Candidate ID": "1676272", "Name": "Mekdes Hailu", "Email": "mekdeshailu19@gmail.com", "Profession": "RESP", "Specialty": "RRT(4)" },
    { "Candidate ID": "1679237", "Name": "Dudlene Jean Pierre", "Email": "Duds2986@gmail.com", "Profession": "RN", "Specialty": "ER(2)" },
    { "Candidate ID": "1688790", "Name": "Jacqueline Judie", "Email": "jackiejudie15@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(6)" },
    { "Candidate ID": "1708793", "Name": "Anniebelle Brattrud", "Email": "annie_brattrud@yahoo.com", "Profession": "RN", "Specialty": "CASEMGR(4)" },
    { "Candidate ID": "1712384", "Name": "Elizabeth Schnolis", "Email": "lizzie1996@me.com", "Profession": "RN", "Specialty": "PEDS-ER(3)" },
    { "Candidate ID": "1714117", "Name": "Kara King", "Email": "KKING01992@GMAIL.COM", "Profession": "LVN", "Specialty": "ADMIN(2)" },
    { "Candidate ID": "1715900", "Name": "Jules Gabriel", "Email": "julesgabriel08@gmail.com", "Profession": "RESP", "Specialty": "RRT(6)" },
    { "Candidate ID": "1726375", "Name": "Teresa Walker", "Email": "teresa_wlkr@yahoo.com", "Profession": "RESP", "Specialty": "RRT-NICU(4) RRT(11)" },
    { "Candidate ID": "1751823", "Name": "Mary Kargbo", "Email": "marykargbo86@yahoo.com", "Profession": "RN", "Specialty": "TELE(1) MS/TELE(5)" },
    { "Candidate ID": "1762704", "Name": "Theresa Obeng", "Email": "thessyobeng80@gmail.com", "Profession": "SURG", "Specialty": "STERILE-TECH(4)" },
    { "Candidate ID": "1793596", "Name": "Kentrell White", "Email": "kentrellftw@gmail.com", "Profession": "SPORT", "Specialty": "EXERPHS(8)" },
    { "Candidate ID": "1799066", "Name": "Merrick Barker", "Email": "mdbarker23@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(7)" },
    { "Candidate ID": "1812576", "Name": "Pauline Anne Abella", "Email": "paulineanne.abella@gmail.com", "Profession": "SURG", "Specialty": "OR-TECH(5)" },
    { "Candidate ID": "1817259", "Name": "Melody Shideler", "Email": "melodylc81@gmail.com", "Profession": "LVN", "Specialty": "LTC(5)" },
    { "Candidate ID": "1840898", "Name": "LaSonya Barnes", "Email": "lasonyabarnes@gmail.com", "Profession": "SURG", "Specialty": "" },
    { "Candidate ID": "1847529", "Name": "Mary Okoye", "Email": "marykerryy@gmail.com", "Profession": "LVN", "Specialty": "LTC(4)" },
    { "Candidate ID": "1865022", "Name": "Leslee Whidden", "Email": "lesleegwhidden@aol.com", "Profession": "RN", "Specialty": "ER(1)" },
    { "Candidate ID": "1865945", "Name": "Alexandre Wing", "Email": "hello@alexandrewing.com", "Profession": "RESP", "Specialty": "RRT(9)" },
    { "Candidate ID": "1912306", "Name": "Carla Bowers", "Email": "cbowers1111@gmail.com", "Profession": "RN", "Specialty": "OR(4)" },
    { "Candidate ID": "1943183", "Name": "Lettice Cobb", "Email": "lettice64@gmail.com", "Profession": "SURG", "Specialty": "OR-TECH(5)" },
    { "Candidate ID": "1956613", "Name": "Margaret Howard", "Email": "meg.howard16@gmail.com", "Profession": "RN", "Specialty": "PICU(3)" },
    { "Candidate ID": "1959378", "Name": "Mark Bodnar", "Email": "agentbodnar@gmail.com", "Profession": "RESP", "Specialty": "RCP(7)" },
    { "Candidate ID": "2387080", "Name": "Hope Palacio", "Email": "hope.palacio@icloud.com", "Profession": "SoclSrvcs", "Specialty": "MED-SW(4)" },
    { "Candidate ID": "2400854", "Name": "Calissa Tessin", "Email": "ctessin@hotmail.com", "Profession": "RN", "Specialty": "OR(2)" },
    { "Candidate ID": "2420298", "Name": "Nicole Washington", "Email": "mccoynicole@rocketmail.com", "Profession": "ER-TECH", "Specialty": "ER-TECH(2)" },
    { "Candidate ID": "2462406", "Name": "Aleah Cawthon", "Email": "mscawthon@gmail.com", "Profession": "PCT", "Specialty": "" },
    { "Candidate ID": "2489703", "Name": "Maryellen Ngo", "Email": "ngolove8@gmail.com", "Profession": "RN", "Specialty": "ICU(14)" },
    { "Candidate ID": "2501327", "Name": "Samantha Zeppi", "Email": "samanthazeppi@gmail.com", "Profession": "OPTH", "Specialty": "OPTH-TECH(9)" },
    { "Candidate ID": "2522838", "Name": "India Hamilton", "Email": "indiaanicole96@gmail.com", "Profession": "CNA", "Specialty": "ER(4)" },
    { "Candidate ID": "2569486", "Name": "Rhiza Mae Madrid", "Email": "Rhizamadrid.rn@gmail.com", "Profession": "RN", "Specialty": "L& D(4)" },
    { "Candidate ID": "2588867", "Name": "Belinda Warren", "Email": "bbelinda46@gmail.com", "Profession": "LAB", "Specialty": "PHLEB(20)" },
    { "Candidate ID": "2615117", "Name": "Amber Akers", "Email": "amberrakers86@gmail.com", "Profession": "RN", "Specialty": "MS(5)" },
    { "Candidate ID": "2638910", "Name": "Jane Turner", "Email": "jane@turner.as", "Profession": "RESP", "Specialty": "RRT(19)" },
    { "Candidate ID": "2661517", "Name": "Suzette Forrest", "Email": "yetzy6@gmail.com", "Profession": "RESP", "Specialty": "RRT(21)" },
    { "Candidate ID": "2704159", "Name": "Kathryn Nordone", "Email": "nordoneke@gmail.com", "Profession": "RN", "Specialty": "PEDS(5)" },

    // BATCH 6
    { "Candidate ID": "2710664", "Name": "Ashley Ellis", "Email": "arothbard5678@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(0) RRT(7)" },
    { "Candidate ID": "2724343", "Name": "Marcie Lanning", "Email": "Marciewolfe@hotmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(15) RRT(26)" },
    { "Candidate ID": "2744391", "Name": "Jeremy Jeter", "Email": "jjeter0104@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(6) RRT(12)" },
    { "Candidate ID": "2800698", "Name": "Jennifer Davenport", "Email": "jdaven01@gmail.com", "Profession": "RESP", "Specialty": "RRT-NICU(0) RRT(17)" },
    { "Candidate ID": "2804038", "Name": "Noemie Valdez", "Email": "noemie.valdez1991@gmail.com", "Profession": "SURG", "Specialty": "ANEST-TECH(9)" },
    { "Candidate ID": "2817187", "Name": "Vivian Coleman", "Email": "vivianobrien27@gmail.com", "Profession": "RN", "Specialty": "PEDS(2)" },
    { "Candidate ID": "2831206", "Name": "Jodi Goodson", "Email": "jodi.furlong36@gmail.com", "Profession": "RESP", "Specialty": "POLY-SLEEP(12)" },
    { "Candidate ID": "2838489", "Name": "Vonderrica Martin", "Email": "vonderrica.martin@yahoo.com", "Profession": "RN", "Specialty": "STEP(4)" },
    { "Candidate ID": "2839041", "Name": "Loa-Le Froneberger", "Email": "chocolatelvr@prodigy.net", "Profession": "RESP", "Specialty": "CRT(4)" },
    { "Candidate ID": "2846891", "Name": "Deja Walters", "Email": "dejawalters15@gmail.com", "Profession": "CNA", "Specialty": "LTC(3)" },
    { "Candidate ID": "2858263", "Name": "Alisa Freeman", "Email": "angiordano213@gmail.com", "Profession": "ER-TECH", "Specialty": "ER-TECH(4)" },
    { "Candidate ID": "2863245", "Name": "Dawn Warr", "Email": "dawn1311979@gmail.com", "Profession": "PCT", "Specialty": "PCTECH(18)" },
    { "Candidate ID": "2890104", "Name": "Amber Dean", "Email": "amber.dean1@outlook.com", "Profession": "RESP", "Specialty": "RRT(10)" },
    { "Candidate ID": "2923128", "Name": "Felipe Duarte", "Email": "duartefelipe510@gmail.com", "Profession": "RESP", "Specialty": "RRT(2)" },
    { "Candidate ID": "2984724", "Name": "Esther Kumuyi", "Email": "estherkumuyi@yahoo.com", "Profession": "RN", "Specialty": "MS(1)" },
    { "Candidate ID": "3005180", "Name": "Stephanie Secontine", "Email": "sgsecontine@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(20)" },
    { "Candidate ID": "3053197", "Name": "Leona Johnson", "Email": "homesbyjohnsons@comcast.net", "Profession": "RESP", "Specialty": "POLY-SLEEP(14)" },
    { "Candidate ID": "3074536", "Name": "Amy McCully", "Email": "aemccully@gmail.com", "Profession": "RN", "Specialty": "ER(8)" },
    { "Candidate ID": "3090970", "Name": "Donna Arrigo", "Email": "darrigo28@sbcglobal.net", "Profession": "RN", "Specialty": "ICU(25)" },
    { "Candidate ID": "3122923", "Name": "Ashley Lyons", "Email": "Arlyons10@gmail.com", "Profession": "RN", "Specialty": "BH(1)" },
    { "Candidate ID": "3131016", "Name": "Gilda Efem", "Email": "Ge_odukoya@yahoo.com", "Profession": "RESP", "Specialty": "RRT(17)" },
    { "Candidate ID": "3172260", "Name": "Jeddrey Aquino", "Email": "jeddrey.aquino@gmail.com", "Profession": "RN", "Specialty": "ICU(3)" },
    { "Candidate ID": "3449863", "Name": "Alexandra Wesley", "Email": "alexandra.nursing.anes@gmail.com", "Profession": "RN", "Specialty": "CVICU(2)" },
    { "Candidate ID": "3449986", "Name": "Cecilia Guzman", "Email": "ceciguzman004@gmail.com", "Profession": "RESP", "Specialty": "RRT(7)" },
    { "Candidate ID": "3495980", "Name": "Bailey Abadie", "Email": "babadie123@gmail.com", "Profession": "RN", "Specialty": "PICU(1)" },
    { "Candidate ID": "3574259", "Name": "Catherine Reyes", "Email": "downtownburbank@yahoo.com", "Profession": "LVN", "Specialty": "ER(2)" },
    { "Candidate ID": "3595107", "Name": "Angela Pavlak", "Email": "Ngpavlak@gmail.com", "Profession": "RESP", "Specialty": "RRT(14)" },
    { "Candidate ID": "3655114", "Name": "Rose Laure Coichy", "Email": "clamercie@yahoo.com", "Profession": "LVN", "Specialty": "BH(3)" },
    { "Candidate ID": "3666906", "Name": "Elizabeth Aung", "Email": "mikidah@icloud.com", "Profession": "RESP", "Specialty": "RRT(2)" },
    { "Candidate ID": "3676672", "Name": "Rebekah White", "Email": "wrebekah@ymail.com", "Profession": "RN", "Specialty": "DIAL(3)" },
    { "Candidate ID": "3683680", "Name": "June Daly", "Email": "jdaly246@gmail.com", "Profession": "RN", "Specialty": "ER(20)" },
    { "Candidate ID": "3740773", "Name": "Brooke Rich", "Email": "brookerich1010@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(2)" },
    { "Candidate ID": "3801743", "Name": "Kristopher Simms", "Email": "Kris_sim24@hotmail.com", "Profession": "RESP", "Specialty": "RRT(12)" },
    { "Candidate ID": "3846611", "Name": "Lisa Davis", "Email": "lisadavis42081@gmail.com", "Profession": "RN", "Specialty": "TELE(7)" },
    { "Candidate ID": "3867291", "Name": "Emily Coker", "Email": "Emcoker7@gmail.com", "Profession": "RN", "Specialty": "OUTP-CLNC(0)" },
    { "Candidate ID": "3883187", "Name": "Ryan Jensen", "Email": "ryancjensen00@gmail.com", "Profession": "LAB", "Specialty": "PHLEB(17)" },
    { "Candidate ID": "3892453", "Name": "Jojean Lorenzana", "Email": "Imeyalorenzana@gmail.com", "Profession": "SURG", "Specialty": "OR-TECH(3)" },
    { "Candidate ID": "3927695", "Name": "Angela Cadreau", "Email": "Angie0130@yahoo.com", "Profession": "RN", "Specialty": "MS(2)" },
    { "Candidate ID": "3933913", "Name": "Ayesha Waseem", "Email": "wayesha23@gmail.com", "Profession": "RESP", "Specialty": "RRT(2)" },
    { "Candidate ID": "3972236", "Name": "Laura Noyes", "Email": "lnoyeshb@aol.com", "Profession": "RN", "Specialty": "CASEMGR(20)" },
    { "Candidate ID": "3978692", "Name": "Kimberly Madden", "Email": "kimmy.ann.madden@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(5)" },
    { "Candidate ID": "4009010", "Name": "Ekomo Clayton", "Email": "charlie.jaguar2013@gmail.com", "Profession": "PCT", "Specialty": "PCTECH(9)" },
    { "Candidate ID": "4030243", "Name": "Jamie Snipes", "Email": "jalysse33@gmail.com", "Profession": "RN", "Specialty": "MS(1)" },
    { "Candidate ID": "4037999", "Name": "Connor Hayton", "Email": "connor.hayton.5@gmail.com", "Profession": "RN", "Specialty": "ER(1)" },
    { "Candidate ID": "4042680", "Name": "Therese Franzese", "Email": "theresefranzese@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(25)" },
    { "Candidate ID": "4056306", "Name": "Mariciel Sacay", "Email": "ancop777.ms@gmail.com", "Profession": "RN", "Specialty": "PACU(2)" },
    { "Candidate ID": "4132893", "Name": "Matthue Tompkins", "Email": "matthuetompkins@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(7)" },
    { "Candidate ID": "4156652", "Name": "Tyler Arrington", "Email": "gabby96.ta@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(2)" },
    { "Candidate ID": "4189630", "Name": "Joseph Grantham", "Email": "Josephgranthamrn@gmail.com", "Profession": "RN", "Specialty": "ER(2)" },
    { "Candidate ID": "4196648", "Name": "Oscar Grimaldo", "Email": "oscar_grimaldo52@yahoo.com", "Profession": "SPORT", "Specialty": "EXERPHS(2)" },
    { "Candidate ID": "4218567", "Name": "Julius Okwu", "Email": "chima47@aol.com", "Profession": "PHYS", "Specialty": "RADONC(18)" },
    { "Candidate ID": "4274545", "Name": "Alexander Anisimov", "Email": "aanisimov.prof@gmail.com", "Profession": "RESP", "Specialty": "RRT(4)" },
    { "Candidate ID": "4295127", "Name": "Scarlett Wilder", "Email": "scarlettgwilder@icloud.com", "Profession": "RN", "Specialty": "CritCarBedMon(1)" },
    { "Candidate ID": "4333277", "Name": "Rochelle Padilla", "Email": "rochelle822000@gmail.com", "Profession": "MA", "Specialty": "URGNT(5)" },
    { "Candidate ID": "4455167", "Name": "Shelby La Mond", "Email": "lamondshelby@gmail.com", "Profession": "SCH", "Specialty": "SCH PSYCH(1)" },

    // BATCH 7
    { "Candidate ID": "4460810", "Name": "Diego Garzon", "Email": "Dieggarzon333@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(3)" },
    { "Candidate ID": "4474804", "Name": "Beverly Wong", "Email": "beverly.t.wong@gmail.com", "Profession": "LAB", "Specialty": "CLS(16)" },
    { "Candidate ID": "4537519", "Name": "Madison Dow", "Email": "madison_dow@icloud.com", "Profession": "RESP", "Specialty": "RRT-NICU(2)" },
    { "Candidate ID": "4556619", "Name": "Aba Mills", "Email": "akyere.mills7@gmail.com", "Profession": "RN", "Specialty": "MS(2)" },
    { "Candidate ID": "4587841", "Name": "Vanessa Clermont", "Email": "vclermont29@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(5)" },
    { "Candidate ID": "4599086", "Name": "Jocelyn Artiaga", "Email": "jocelynartiaga@yahoo.com", "Profession": "RESP", "Specialty": "RRT-NICU(2)" },
    { "Candidate ID": "4653317", "Name": "Collin Weller", "Email": "cjw761@outlook.com", "Profession": "OPTH", "Specialty": "OPTH-TECH(24)" },
    { "Candidate ID": "4728532", "Name": "Candy Jones", "Email": "pumpgirl64@yahoo.com", "Profession": "PERF", "Specialty": "PERF(25)" },
    { "Candidate ID": "4741723", "Name": "Shanell Torchia", "Email": "torchiashanell@icloud.com", "Profession": "LVN", "Specialty": "BH(2)" },
    { "Candidate ID": "4748603", "Name": "Melissa Rivera", "Email": "melissarivera5700@gmail.com", "Profession": "RN", "Specialty": "AMB(1)" },
    { "Candidate ID": "4767763", "Name": "Fausto Moscat", "Email": "esteven123@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(2)" },
    { "Candidate ID": "4778705", "Name": "aubrey meyer", "Email": "aubrey18meyer@gmail.com", "Profession": "RESP", "Specialty": "RRT(3)" },
    { "Candidate ID": "4782819", "Name": "Leonard Becerra", "Email": "lennybecerrarn@gmail.com", "Profession": "RN", "Specialty": "MICU(3)" },
    { "Candidate ID": "4795106", "Name": "Ilona Cudiamat", "Email": "ilonacudiamat@gmail.com", "Profession": "RN", "Specialty": "RNSNF(2)" },
    { "Candidate ID": "4798018", "Name": "Reynel Tecruceno", "Email": "reynelt107@gmail.com", "Profession": "RN", "Specialty": "ER(4)" },
    { "Candidate ID": "4802444", "Name": "Yolanda Watson", "Email": "ywloni@yahoo.com", "Profession": "RESP", "Specialty": "CRT(25)" },
    { "Candidate ID": "4812600", "Name": "Kashonda Lacy", "Email": "kashondalacy@yahoo.com", "Profession": "RESP", "Specialty": "RRT-NICU(15)" },
    { "Candidate ID": "4862585", "Name": "Andrea Wright", "Email": "andreajean.AL@gmail.com", "Profession": "RESP", "Specialty": "RRT(10)" },
    { "Candidate ID": "4901598", "Name": "Cassie Hall", "Email": "cassiehall143@yahoo.com", "Profession": "RESP", "Specialty": "RRT(5)" },
    { "Candidate ID": "4901720", "Name": "Reed Vance-Stokes", "Email": "reedvs@comcast.net", "Profession": "RN", "Specialty": "L& D(2)" },
    { "Candidate ID": "4906002", "Name": "Danielle Samelson", "Email": "samelsond@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(5)" },
    { "Candidate ID": "4921442", "Name": "Joshua Nichols", "Email": "jd.nichols8923@gmail.com", "Profession": "LAB", "Specialty": "HST-TCH(4)" },
    { "Candidate ID": "4932027", "Name": "Mark Brock", "Email": "phuchxph@gmail.com", "Profession": "RESP", "Specialty": "RRT(6)" },
    { "Candidate ID": "4932099", "Name": "Taylor Burton", "Email": "taylorlynnb111@gmail.com", "Profession": "DietSrv", "Specialty": "DIET(3)" },
    { "Candidate ID": "4939855", "Name": "FERNANDO ALEMAN", "Email": "faleman18@gmail.com", "Profession": "RAD-CARD", "Specialty": "MRI(7)" },
    { "Candidate ID": "4952743", "Name": "Juliana Wilson", "Email": "wj330921@outlook.com", "Profession": "PHM", "Specialty": "PhrmTech-Inp(12)" },
    { "Candidate ID": "5024222", "Name": "Jill Shock", "Email": "jshock1932@gmail.com", "Profession": "RESP", "Specialty": "RRT(24)" },
    { "Candidate ID": "5042715", "Name": "Angelique Pastera", "Email": "chilipaste1990@gmail.com", "Profession": "RN", "Specialty": "MS(10)" },
    { "Candidate ID": "5046407", "Name": "Calvin Smith", "Email": "calvinsmith69@icloud.com", "Profession": "LAB", "Specialty": "PHLEB(20)" },
    { "Candidate ID": "5048061", "Name": "Benjamin White", "Email": "bdwhite@email.meredith.edu", "Profession": "DietSrv", "Specialty": "PedDiet(3)" }
  ]
};
fs.writeFileSync("/Users/k.far.88/Documents/New project/thelab/scratch/payload_all.json", JSON.stringify(payload, null, 2));
console.log("Master payload saved.");
